import { describe, expect, it } from "vitest";
import { renderFailureEmail, renderSummaryEmail } from "./index";

describe("email renderer", () => {
  it("renders summary text and html snapshots", () => {
    const rendered = renderSummaryEmail({
      subject: "Project sync",
      summary: {
        meetingType: "general",
        meetingNotes: [
          {
            heading: "Key Discussion Topics:",
            overview: "The launch path was reviewed.",
            items: [{ title: "Launch Readiness:", detail: "Alex reviewed launch readiness and confirmed release notes still need to be shipped." }]
          }
        ],
        followUpTasks: [{ title: "Ship Release Notes:", description: "Ship release notes for the launch package.", owners: ["Alex"], dueDate: "TBD" }],
        summary: ["Discussed launch."],
        decisions: [],
        actionItems: [{ owner: "Alex", task: "Ship release notes", dueDate: "TBD" }],
        openQuestions: [],
        risks: [],
        followUps: []
      },
      excludedRecipients: ["vendor@example.com"]
    });

    expect(rendered.subject).toBe("Meeting summary: Project sync");
    expect(rendered.text).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(rendered.text).toContain("Meeting type: General");
    expect(rendered.text).toContain("Meeting notes:");
    expect(rendered.text).toContain("Key Discussion Topics:");
    expect(rendered.text).toContain("Launch Readiness:");
    expect(rendered.text).toContain("Follow-up tasks:");
    expect(rendered.text).toContain("Ship Release Notes:");
    expect(rendered.text).toContain("Ship release notes for the launch package. (Alex) Due: TBD");
    expect(rendered.html).toContain("<li>vendor@example.com</li>");
    expect(rendered.html).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(rendered.html).toContain("<h2>Meeting notes</h2>");
    expect(rendered.html).toContain("<h3>Key Discussion Topics:</h3>");
    expect(rendered.html).toContain("<strong>Launch Readiness:</strong>");
    expect(rendered.html).toContain("<h2>Follow-up tasks</h2>");
  });

  it("renders organizer-only failure notices", () => {
    expect(renderFailureEmail({ subject: "Project sync" }).subject).toBe("Notes unavailable: Project sync");
  });

  it("renders recap layout settings in configured order", () => {
    const rendered = renderSummaryEmail({
      subject: "Project sync",
      summary: {
        meetingType: "general",
        meetingNotes: [
          {
            heading: "Key Discussion Topics:",
            overview: "The launch checklist was reviewed.",
            items: [{ title: "Launch Checklist:", detail: "The team reviewed checklist ownership and training gaps." }]
          }
        ],
        followUpTasks: [{ title: "Ship Release Notes:", description: "Ship release notes for the launch package.", owners: ["Alex"], dueDate: "TBD" }],
        summary: ["Discussed launch."],
        decisions: ["Launch Friday."],
        actionItems: [{ owner: "Alex", task: "Ship release notes", dueDate: "TBD" }],
        openQuestions: ["Who owns training?"],
        risks: ["Schedule compression."],
        followUps: ["Review launch checklist."]
      },
      recap: {
        subjectPrefix: "Recap",
        introText: "Here is the meeting recap.",
        sections: [
          { key: "actionItems", label: "Next steps", enabled: true },
          { key: "summary", label: "Overview", enabled: true },
          { key: "risks", label: "Risks", enabled: false }
        ]
      }
    });

    expect(rendered.subject).toBe("Recap: Project sync");
    expect(rendered.text).toContain("Follow-up tasks:");
    expect(rendered.text).not.toContain("Next steps");
    expect(rendered.text).toContain("Here is the meeting recap.");
    expect(rendered.text).not.toContain("Schedule compression.");
    expect(rendered.html).toContain("<p>Here is the meeting recap.</p>");
  });

  it("renders meeting type in plain text and html and treats legacy summaries as general", () => {
    const typed = renderSummaryEmail({
      subject: "Weekly Sales",
      summary: {
        meetingType: "weekly_sales",
        meetingNotes: [
          {
            heading: "Sales Pipeline and Forecast Updates:",
            overview: "Forecast movement was reviewed.",
            items: [{ title: "Forecast Movement:", detail: "Forecast moved up based on current pipeline movement." }]
          }
        ],
        followUpTasks: [],
        summary: ["Meeting type: Weekly Sales", "Sales forecast/pipeline: Forecast moved up."],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      }
    });
    const legacy = renderSummaryEmail({
      subject: "Old summary",
      summary: {
        summary: ["Discussed launch."],
        decisions: [],
        actionItems: [],
        openQuestions: [],
        risks: [],
        followUps: []
      }
    });

    expect(typed.text).toContain("Meeting type: Weekly Sales");
    expect(typed.html).toContain("Meeting type: Weekly Sales");
    expect(legacy.text).toContain("Generated by AI. Be sure to check for accuracy.");
    expect(legacy.text).toContain("Meeting type: General");
    expect(legacy.text).toContain("Summary");
  });
});
