import { meetingRecapTypeLabels } from "@minutesbot/summary-engine";
import type { RenderedEmail, SummaryEmailInput, SummaryEmailSummary } from "./types";

const aiDisclaimer = "Generated by AI. Be sure to check for accuracy.";

export function renderSummaryEmail(input: SummaryEmailInput): RenderedEmail {
  const summary = normalizeSummary(input.summary);
  const meetingTypeLabel = meetingRecapTypeLabels[summary.meetingType];
  const recapDepthLabel = summary.recapDepth === "brief" ? "Brief" : "Standard";
  const text = renderText({ ...input, summary }, meetingTypeLabel, recapDepthLabel);
  const html = renderHtml({ ...input, summary }, meetingTypeLabel, recapDepthLabel);
  return { subject: `${input.recap?.subjectPrefix ?? "Meeting summary"}: ${input.subject}`, text, html };
}

function normalizeSummary(summary: SummaryEmailSummary): Required<Pick<SummaryEmailSummary, "meetingType" | "recapDepth" | "meetingNotes" | "followUpTasks">> & SummaryEmailSummary {
  return {
    ...summary,
    meetingType: summary.meetingType ?? "general",
    recapDepth: summary.recapDepth ?? "standard",
    meetingNotes: summary.meetingNotes ?? [],
    followUpTasks: summary.followUpTasks ?? []
  };
}

function renderText(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  return [
    aiDisclaimer,
    "",
    "Meeting recap",
    `Subject: ${input.subject}`,
    input.date ? `Date: ${input.date}` : "",
    `Meeting type: ${meetingTypeLabel}`,
    `Recap depth: ${recapDepthLabel}`,
    input.transcriptDownloadUrl ? `Raw transcript: ${input.transcriptDownloadUrl}` : "",
    input.recap?.introText ?? "",
    input.summary.recapDepth === "brief" ? "Brief meeting detected. This recap is simplified because the meeting or captured transcript was very short." : "",
    "",
    "Meeting notes:",
    "",
    ...renderMeetingNotesText(input.summary.meetingNotes),
    "Follow-up tasks:",
    "",
    ...renderFollowUpTasksText(input.summary.followUpTasks),
    ...secondarySections.map((section) => sectionText(section.label, section.items)),
    sectionText("Not sent to external attendees", input.excludedRecipients ?? [])
  ]
    .filter(Boolean)
    .join("\n");
}

function renderHtml(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, meetingTypeLabel: string, recapDepthLabel: string): string {
  const secondarySections = resolveSecondarySections(input, isLegacyOnly(input.summary));
  return [
    '<div style="margin:0;padding:18px;background:#111827;font-family:Inter,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#f8fafc;">',
    '<div style="max-width:720px;margin:0 auto;background:#0b1120;border-radius:10px;overflow:hidden;">',
    '<div style="height:4px;background:#2dd4bf;"></div>',
    '<div style="padding:22px 24px 18px;">',
    '<div style="font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:#5eead4;font-weight:800;">WGS / minutesbot</div>',
    '<h1 style="margin:7px 0 4px;font-size:25px;line-height:1.2;color:#ffffff;">Meeting recap</h1>',
    paragraph(input.subject, "margin:0 0 4px;font-size:17px;line-height:1.42;color:#e5e7eb;font-weight:800;"),
    input.date ? paragraph(input.date, "margin:0 0 12px;font-size:14px;line-height:1.35;color:#cbd5e1;") : "",
    `<div style="display:block;margin:12px 0 0;">${badge(meetingTypeLabel)}${input.summary.recapDepth === "brief" ? badge("Brief recap", "#172554", "#bfdbfe") : ""}</div>`,
    input.transcriptDownloadUrl ? `<p style="margin:12px 0 0;font-size:14px;"><a href="${escapeAttribute(input.transcriptDownloadUrl)}" style="color:#67e8f9;font-weight:800;text-decoration:underline;">Download raw transcript</a></p>` : "",
    callout(aiDisclaimer),
    input.summary.recapDepth === "brief" ? callout("Brief meeting detected<br><span style=\"font-weight:600;\">This recap is simplified because the meeting or captured transcript was very short.</span>", "#083344", "#22d3ee") : "",
    input.recap?.introText ? paragraph(input.recap.introText, "margin:14px 0 0;font-size:14px;line-height:1.5;color:#d1d5db;") : "",
    sectionHeading("Meeting notes"),
    renderMeetingNotesHtml(input.summary.meetingNotes),
    sectionHeading("Follow-up tasks"),
    renderFollowUpTasksHtml(input.summary.followUpTasks),
    secondarySections.map((section) => renderBulletSection(section.label, section.items)).join(""),
    input.excludedRecipients?.length ? renderBulletSection("Not sent to external attendees", input.excludedRecipients) : "",
    '<div style="margin-top:20px;padding-top:12px;border-top:1px solid #334155;color:#cbd5e1;font-size:12px;line-height:1.45;">Sent by minutesbot<br>This recap was generated from the meeting transcript and may require human review.</div>',
    "</div></div></div>"
  ].join("");
}

function renderMeetingNotesText(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string[] {
  if (notes.length === 0) return ["None captured.", ""];
  return notes.flatMap((note) => [
    note.heading,
    note.overview,
    ...note.items.flatMap((item) => [item.title, item.detail, ""]),
    ""
  ]);
}

function renderFollowUpTasksText(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string[] {
  if (tasks.length === 0) return ["No follow-up tasks captured.", ""];
  return tasks.flatMap((task) => [
    task.title,
    task.description,
    `Owner: ${formatOwners(task.owners)}`,
    `Due: ${task.dueDate}`,
    ""
  ]);
}

function renderMeetingNotesHtml(notes: ReturnType<typeof normalizeSummary>["meetingNotes"]): string {
  if (notes.length === 0) return paragraph("None captured.", "margin:0 0 12px;font-size:14px;color:#cbd5e1;");
  return notes
    .map(
      (note) =>
        `<div style="margin:0 0 12px;padding:0 0 12px;border-bottom:1px solid #1f2937;">` +
        `<h3 style="margin:0 0 6px;font-size:16px;color:#ffffff;">${escapeHtml(note.heading)}</h3>` +
        (note.overview ? paragraph(note.overview, "margin:0 0 10px;font-size:14px;line-height:1.5;color:#d1d5db;") : "") +
        note.items
          .map((item) => `<p style="margin:8px 0 3px;font-size:14px;color:#f8fafc;"><strong>${escapeHtml(item.title)}</strong></p>${paragraph(item.detail, "margin:0;font-size:14px;line-height:1.5;color:#d1d5db;")}`)
          .join("") +
        "</div>"
    )
    .join("");
}

function renderFollowUpTasksHtml(tasks: ReturnType<typeof normalizeSummary>["followUpTasks"]): string {
  if (tasks.length === 0) return paragraph("No follow-up tasks captured.", "margin:0 0 12px;font-size:14px;color:#cbd5e1;");
  return tasks
    .map(
      (task) =>
        `<div style="margin:0 0 10px;padding:0 0 0 10px;border-left:3px solid #2dd4bf;">` +
        `<p style="margin:0 0 4px;font-size:14px;color:#f8fafc;"><strong>${escapeHtml(task.title)}</strong></p>` +
        paragraph(task.description, "margin:0 0 6px;font-size:14px;line-height:1.5;color:#d1d5db;") +
        paragraph(`Owner: ${formatOwners(task.owners)}`, "margin:0 0 3px;font-size:13px;color:#cbd5e1;") +
        paragraph(`Due: ${task.dueDate}`, "margin:0;font-size:13px;color:#cbd5e1;") +
        "</div>"
    )
    .join("");
}

function resolveLegacySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }): Array<{ label: string; items: string[] }> {
  const includeActionItems = input.summary.followUpTasks.length === 0;
  const values = {
    summary: input.summary.summary,
    decisions: input.summary.decisions,
    actionItems: includeActionItems ? input.summary.actionItems.map((item) => [item.owner, item.task, item.dueDate].filter(Boolean).join(" - ")) : [],
    openQuestions: input.summary.openQuestions,
    risks: input.summary.risks,
    followUps: input.summary.followUps
  };
  const defaultSections: NonNullable<SummaryEmailInput["recap"]>["sections"] = [
    { key: "summary", label: "Summary", enabled: true },
    { key: "decisions", label: "Decisions", enabled: true },
    { key: "actionItems", label: "Action items", enabled: true },
    { key: "openQuestions", label: "Open questions", enabled: true },
    { key: "risks", label: "Risks", enabled: true },
    { key: "followUps", label: "Follow-ups", enabled: true }
  ];
  return (input.recap?.sections ?? defaultSections)
    .filter((section) => section.enabled)
    .map((section) => ({ label: section.label, items: values[section.key] }));
}

function resolveSecondarySections(input: SummaryEmailInput & { summary: ReturnType<typeof normalizeSummary> }, includeLegacySummary = false): Array<{ label: string; items: string[] }> {
  const labels = includeLegacySummary ? ["Summary", "Decisions", "Open questions", "Risks", "Follow-ups"] : ["Decisions", "Open questions", "Risks"];
  return resolveLegacySections(input).filter((section) => labels.includes(section.label) && section.items.length > 0);
}

function sectionText(title: string, items: string[]): string {
  if (items.length === 0) return "";
  return `${title}\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function renderBulletSection(title: string, items: string[]): string {
  if (items.length === 0) return "";
  const listItems = items.map((item) => `<li style="margin:0 0 5px;">${escapeHtml(item)}</li>`).join("");
  return `${sectionHeading(title)}<ul style="margin:0 0 12px 20px;padding:0;font-size:14px;line-height:1.5;color:#d1d5db;">${listItems}</ul>`;
}

function sectionHeading(value: string): string {
  return `<h2 style="margin:22px 0 10px;padding-bottom:6px;border-bottom:1px solid #334155;font-size:18px;line-height:1.3;color:#ffffff;">${escapeHtml(value)}</h2>`;
}

function badge(value: string, background = "#134e4a", color = "#ccfbf1"): string {
  return `<span style="display:inline-block;margin:0 6px 6px 0;padding:4px 9px;border-radius:999px;background:${background};color:${color};font-size:12px;font-weight:800;">${escapeHtml(value)}</span>`;
}

function callout(value: string, background = "#422006", border = "#facc15"): string {
  return `<div style="margin:14px 0 0;padding:10px 12px;border-left:3px solid ${border};background:${background};font-size:14px;line-height:1.45;color:#fef3c7;font-weight:800;">${value}</div>`;
}

function paragraph(value: string, style: string): string {
  return `<p style="${style}">${escapeHtml(value)}</p>`;
}

function formatOwners(owners: string[]): string {
  return owners.length > 0 ? owners.join(", ") : "Unassigned";
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replaceAll("'", "&#39;");
}

function isLegacyOnly(summary: ReturnType<typeof normalizeSummary>): boolean {
  return summary.meetingNotes.length === 0 && summary.followUpTasks.length === 0;
}
