import { meetingRecapTypeLabels } from "@minutesbot/summary-engine";
import type { RenderedEmail, SummaryEmailInput } from "./types";

const aiDisclaimer = "Generated by AI. Be sure to check for accuracy.";

export function renderSummaryEmail(input: SummaryEmailInput): RenderedEmail {
  const meetingTypeLabel = meetingRecapTypeLabels[input.summary.meetingType ?? "general"];
  const hasTeamsStyle = hasTeamsStyleSummary(input.summary);
  const text = hasTeamsStyle ? renderTeamsStyleText(input, meetingTypeLabel) : renderLegacyText(input, meetingTypeLabel);
  const html = hasTeamsStyle ? renderTeamsStyleHtml(input, meetingTypeLabel) : renderLegacyHtml(input, meetingTypeLabel);
  return { subject: `${input.recap?.subjectPrefix ?? "Meeting summary"}: ${input.subject}`, text, html };
}

function hasTeamsStyleSummary(summary: SummaryEmailInput["summary"]): boolean {
  return Boolean(summary.meetingNotes?.length || summary.followUpTasks?.length);
}

function renderTeamsStyleText(input: SummaryEmailInput, meetingTypeLabel: string): string {
  const secondarySections = resolveSecondarySections(input);
  return [
    aiDisclaimer,
    "",
    "Meeting",
    input.subject,
    input.date ?? "",
    input.recap?.introText ?? "",
    `Meeting type: ${meetingTypeLabel}`,
    "",
    "Meeting notes:",
    "",
    ...renderMeetingNotesText(input.summary.meetingNotes ?? []),
    "Follow-up tasks:",
    "",
    ...renderFollowUpTasksText(input.summary.followUpTasks ?? []),
    ...secondarySections.map((section) => sectionText(section.label, section.items)),
    sectionText("Not sent to external attendees", input.excludedRecipients ?? [])
  ]
    .filter(Boolean)
    .join("\n");
}

function renderLegacyText(input: SummaryEmailInput, meetingTypeLabel: string): string {
  const sections = resolveLegacySections(input);
  return [
    aiDisclaimer,
    "",
    "Meeting",
    input.subject,
    input.date ?? "",
    input.recap?.introText ?? "",
    `Meeting type: ${meetingTypeLabel}`,
    "",
    ...sections.map((section) => sectionText(section.label, section.items)),
    sectionText("Not sent to external attendees", input.excludedRecipients ?? [])
  ]
    .filter(Boolean)
    .join("\n");
}

function renderTeamsStyleHtml(input: SummaryEmailInput, meetingTypeLabel: string): string {
  const secondarySections = resolveSecondarySections(input);
  return `<main>${paragraph(aiDisclaimer, "aiDisclaimer")}${heading("Meeting")}${paragraph(input.subject)}${input.date ? paragraph(input.date) : ""}${input.recap?.introText ? paragraph(input.recap.introText) : ""}${paragraph(`Meeting type: ${meetingTypeLabel}`, "meetingTypeLine")}${heading("Meeting notes")}${renderMeetingNotesHtml(input.summary.meetingNotes ?? [])}${heading("Follow-up tasks")}${renderFollowUpTasksHtml(input.summary.followUpTasks ?? [])}${secondarySections.map((section) => sectionHtml(section.label, section.items)).join("")}${sectionHtml("Not sent to external attendees", input.excludedRecipients ?? [])}</main>`;
}

function renderLegacyHtml(input: SummaryEmailInput, meetingTypeLabel: string): string {
  const sections = resolveLegacySections(input);
  return `<main>${paragraph(aiDisclaimer, "aiDisclaimer")}${heading("Meeting")}${paragraph(input.subject)}${input.date ? paragraph(input.date) : ""}${input.recap?.introText ? paragraph(input.recap.introText) : ""}${paragraph(`Meeting type: ${meetingTypeLabel}`, "meetingTypeLine")}${sections.map((section) => sectionHtml(section.label, section.items)).join("")}${sectionHtml("Not sent to external attendees", input.excludedRecipients ?? [])}</main>`;
}

function renderMeetingNotesText(notes: NonNullable<SummaryEmailInput["summary"]["meetingNotes"]>): string[] {
  if (notes.length === 0) return ["None", ""];
  return notes.flatMap((note) => [
    note.heading,
    note.overview,
    ...note.items.flatMap((item) => [item.title, item.detail, ""]),
    ""
  ]);
}

function renderFollowUpTasksText(tasks: NonNullable<SummaryEmailInput["summary"]["followUpTasks"]>): string[] {
  if (tasks.length === 0) return ["None", ""];
  return tasks.flatMap((task) => [
    task.title,
    `${task.description} (${formatOwners(task.owners)}) Due: ${task.dueDate}`,
    ""
  ]);
}

function renderMeetingNotesHtml(notes: NonNullable<SummaryEmailInput["summary"]["meetingNotes"]>): string {
  if (notes.length === 0) return paragraph("None");
  return notes
    .map(
      (note) =>
        `<section>${subheading(note.heading)}${note.overview ? paragraph(note.overview) : ""}${note.items
          .map((item) => `<p><strong>${escapeHtml(item.title)}</strong></p>${paragraph(item.detail)}`)
          .join("")}</section>`
    )
    .join("");
}

function renderFollowUpTasksHtml(tasks: NonNullable<SummaryEmailInput["summary"]["followUpTasks"]>): string {
  if (tasks.length === 0) return paragraph("None");
  return tasks
    .map((task) => `<section><p><strong>${escapeHtml(task.title)}</strong></p>${paragraph(`${task.description} (${formatOwners(task.owners)}) Due: ${task.dueDate}`)}</section>`)
    .join("");
}

function resolveLegacySections(input: SummaryEmailInput): Array<{ label: string; items: string[] }> {
  const values = {
    summary: input.summary.summary,
    decisions: input.summary.decisions,
    actionItems: input.summary.actionItems.map((item) => [item.owner, item.task, item.dueDate].filter(Boolean).join(" - ")),
    openQuestions: input.summary.openQuestions,
    risks: input.summary.risks,
    followUps: input.summary.followUps
  };
  const defaultSections: NonNullable<SummaryEmailInput["recap"]>["sections"] = [
    { key: "summary", label: "Summary", enabled: true },
    { key: "decisions", label: "Decisions", enabled: true },
    { key: "actionItems", label: "Action items", enabled: true },
    { key: "openQuestions", label: "Open questions", enabled: true },
    { key: "risks", label: "Risks", enabled: true },
    { key: "followUps", label: "Follow-ups", enabled: true }
  ];
  return (input.recap?.sections ?? defaultSections)
    .filter((section) => section.enabled)
    .map((section) => ({ label: section.label, items: values[section.key] }));
}

function resolveSecondarySections(input: SummaryEmailInput): Array<{ label: string; items: string[] }> {
  const sections = resolveLegacySections(input);
  return sections.filter((section) => ["Decisions", "Open questions", "Risks"].includes(section.label) && section.items.length > 0);
}

function sectionText(title: string, items: string[]): string {
  if (items.length === 0) return `${title}\n- None\n`;
  return `${title}\n${items.map((item) => `- ${item}`).join("\n")}\n`;
}

function sectionHtml(title: string, items: string[]): string {
  const listItems = (items.length ? items : ["None"]).map((item) => `<li>${escapeHtml(item)}</li>`).join("");
  return `${heading(title)}<ul>${listItems}</ul>`;
}

function heading(value: string): string {
  return `<h2>${escapeHtml(value)}</h2>`;
}

function subheading(value: string): string {
  return `<h3>${escapeHtml(value)}</h3>`;
}

function paragraph(value: string, className?: string): string {
  return `<p${className ? ` class="${className}"` : ""}>${escapeHtml(value)}</p>`;
}

function formatOwners(owners: string[]): string {
  return owners.length > 0 ? owners.join(", ") : "Unassigned";
}

function escapeHtml(value: string): string {
  return value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
}
